export const USER_REPO_TOKEN = 'USER_REPO_TOKEN';
export const STUDENT_REPO_TOKEN = 'STUDENT_REPO_TOKEN';
export const ADMIN_REPO_TOKEN = 'ADMIN_REPO_TOKEN';
export const TEACHER_REPO_TOKEN = 'TEACHER_REPO_TOKEN';
