export const USER_REPO_TOKEN = 'USER_REPO_TOKEN';
export const STUDENT_REPO_TOKEN = 'STUDENT_REPO_TOKEN';
export const ADMIN_REPO_TOKEN = 'ADMIN_REPO_TOKEN';
export const TEACHER_REPO_TOKEN = 'TEACHER_REPO_TOKEN';

export const TRANSACTION_REPO_TOKEN = 'TRANSACTION_REPO_TOKEN';
export const TRANSACTION_TYPE_REPO_TOKEN = 'TRANSACTION_TYPE_REPO_TOKEN';
export const TRANSACTION_STATUS_REPO_TOKEN = 'TRANSACTION_STATUS_REPO_TOKEN';
export const BANK_ACCOUNT_REPO_TOKEN = 'BANK_ACCOUNT_REPO_TOKEN';
export const BILL_REPO_TOKEN = 'BILL_REPO_TOKEN';
export const CLASS_PRICE_REPO_TOKEN = 'CLASS_PRICE_REPO_TOKEN';
